version: '3.9'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
  support:
    depends_on:
      - postgres
    build: ./spring-support
    restart: on-failure
  app:
    build: ./python-dashboard
    restart: always
    depends_on:
      - postgres
      - support
    ports:
      - "5000:5000"
  frontend:
    image: httpd:latest
    ports:
      - "80:80"
    volumes:
      - ./react-frontend/build:/usr/local/apache2/htdocs

volumes:
  postgres_data: